/**
 * Nandi Delices - Menu Items Data
 * Transcribed from reference_menu.jpeg and menu.json (37 total items)
 */

const CATEGORIES = [
  { id: "all", nameFr: "Tout le menu", nameEn: "All Menu", icon: "✨" },
  { id: "starters", nameFr: "Snacks / Entrées", nameEn: "Snacks & Starters", icon: "🥟", count: 12 },
  { id: "main-dishes", nameFr: "Plats principaux", nameEn: "Main Dishes", icon: "🍛", count: 21 },
  { id: "special", nameFr: "Spécial / Sur commande", nameEn: "Special / On Order", icon: "⭐", count: 1 },
  { id: "desserts", nameFr: "Desserts", nameEn: "Desserts & Sweets", icon: "🥥", count: 3 }
];

const MENU_ITEMS = [
  // ----------------------------------------------------
  // STARTERS (12 items)
  // ----------------------------------------------------
  {
    id: "1",
    category: "starters",
    nameFr: "Samoussas – Légumes",
    nameEn: "Vegetable Samosas",
    descriptionFr: "Samoussas croustillants garnis de légumes frais épicés et pommes de terre.",
    descriptionEn: "Crispy triangular pastries stuffed with spiced vegetables and potatoes.",
    price: 1.0,
    unit: "pièce",
    available: true,
    isVegetarian: true,
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "2",
    category: "starters",
    nameFr: "Samoussas – Poulet",
    nameEn: "Chicken Samosas",
    descriptionFr: "Pâte feuilletée dorée farcie au poulet haché mijoté aux épices douces.",
    descriptionEn: "Golden crispy pastries stuffed with minced spiced chicken.",
    price: 1.0,
    unit: "pièce",
    available: true,
    isVegetarian: false,
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "3",
    category: "starters",
    nameFr: "Samoussas – Bœuf",
    nameEn: "Beef Samosas",
    descriptionFr: "Samoussas traditionnels au bœuf assaisonné d'herbes et épices parfumées.",
    descriptionEn: "Traditional fried pastries packed with seasoned minced beef.",
    price: 1.0,
    unit: "pièce",
    available: true,
    isVegetarian: false,
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "4",
    category: "starters",
    nameFr: "Samoussas – Crevettes",
    nameEn: "Shrimp Samosas",
    descriptionFr: "Farce savoureuse aux crevettes hachées, coriandre et gingembre.",
    descriptionEn: "Delicate crunchy samosas filled with succulent minced shrimp and herbs.",
    price: 1.0,
    unit: "pièce",
    available: true,
    isVegetarian: false,
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "5",
    category: "starters",
    nameFr: "Samoussas – Fromages",
    nameEn: "Cheese Samosas",
    descriptionFr: "Cœur fondant au fromage râpé fondant et herbes.",
    descriptionEn: "Mouthwatering crispy samosas with rich melted cheese filling.",
    price: 1.0,
    unit: "pièce",
    available: true,
    isVegetarian: true,
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "6",
    category: "starters",
    nameFr: "Samoussas – Chèvre miel",
    nameEn: "Goat Cheese & Honey Samosas",
    descriptionFr: "Subtile alliance sucrée-salée au fromage de chèvre crémeux et touche de miel.",
    descriptionEn: "Delicious sweet & savory fusion of goat cheese and golden honey.",
    price: 1.0,
    unit: "pièce",
    available: true,
    isVegetarian: true,
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "7",
    category: "starters",
    nameFr: "Samoussas – Feta épinard",
    nameEn: "Feta & Spinach Samosas",
    descriptionFr: "Garniture grecque inspirée d'épinards frais et féta savoureuse.",
    descriptionEn: "Crispy pastry stuffed with fresh spinach and tangy Greek feta.",
    price: 1.0,
    unit: "pièce",
    available: true,
    isVegetarian: true,
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "8",
    category: "starters",
    nameFr: "Boulette et bouchons de poulet",
    nameEn: "Chicken Meatballs & Chicken Bouchons",
    descriptionFr: "Bouchées vapeur et frites traditionnelles mauriciennes au poulet fondant.",
    descriptionEn: "Authentic steamed and fried chicken dumplings and savory meatballs.",
    price: 1.0,
    unit: "pièce",
    available: true,
    isVegetarian: false,
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "9",
    category: "starters",
    nameFr: "Accra / Pâté (Thon ou poulet)",
    nameEn: "Accra Fritters / Tuna or Chicken Pâté",
    descriptionFr: "Beignets croustillants d'accras et petits pâtés dorés faits maison.",
    descriptionEn: "Crispy golden Creole accra fritters and savoury tuna/chicken patties.",
    price: 1.0,
    unit: "pièce",
    available: true,
    isVegetarian: false,
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "10",
    category: "starters",
    nameFr: "Bonbons piments",
    nameEn: "Chili Fritters",
    descriptionFr: "Petits beignets croquants de pois cassés jaunes relevés au piment et coriandre.",
    descriptionEn: "Famous Mauritian crispy yellow split-pea fritters with fresh chili & coriander.",
    price: 1.0,
    unit: "pièce",
    available: true,
    isVegetarian: true,
    spiceLevel: 2,
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "11",
    category: "starters",
    nameFr: "Beignet choux et oignons / bonbon piment",
    nameEn: "Cabbage & Onion Fritter / Chili Fritter",
    descriptionFr: "Beignets légers et dorés aux choux râpés, oignons émincés et épices.",
    descriptionEn: "Crispy fritters made of shredded cabbage, sweet onions, and aromatic herbs.",
    price: 1.0,
    unit: "pièce",
    available: true,
    isVegetarian: true,
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "12",
    category: "starters",
    nameFr: "Nems poulet / crevette",
    nameEn: "Chicken / Shrimp Spring Rolls",
    descriptionFr: "Rouleaux croustillants dorés garnis de poulet ou crevettes et vermicelles.",
    descriptionEn: "Crispy fried spring rolls stuffed with tender chicken or shrimp and noodles.",
    price: 1.0,
    unit: "pièce",
    available: true,
    isVegetarian: false,
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80"
  },

  // ----------------------------------------------------
  // MAIN DISHES (21 items)
  // ----------------------------------------------------
  {
    id: "13",
    category: "main-dishes",
    nameFr: "Curry poulet",
    nameEn: "Chicken Curry",
    descriptionFr: "Curry de poulet créole mijoté à feux doux avec pommes de terre et masala maison.",
    descriptionEn: "Authentic slow-cooked chicken curry in homemade Mauritian masala with potatoes.",
    price: 3.8,
    unit: "100g",
    available: true,
    isVegetarian: false,
    spiceLevel: 2,
    popular: true,
    image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "14",
    category: "main-dishes",
    nameFr: "Curry agneau",
    nameEn: "Lamb Curry",
    descriptionFr: "Morceaux d'agneau fondants marinés aux épices torréfiées et sauce onctueuse.",
    descriptionEn: "Tender lamb pieces simmered in rich, aromatic roasted spices gravy.",
    price: 3.8,
    unit: "100g",
    available: true,
    isVegetarian: false,
    spiceLevel: 2,
    popular: true,
    image: "https://images.unsplash.com/photo-1545247181-516773cae754?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "15",
    category: "main-dishes",
    nameFr: "Curry bœuf",
    nameEn: "Beef Curry",
    descriptionFr: "Bœuf savoureux braisé aux épices créoles, ail, gingembre et tomates fraîches.",
    descriptionEn: "Hearty braised beef stew cooked in Creole herbs, fresh garlic, and ginger.",
    price: 3.8,
    unit: "100g",
    available: true,
    isVegetarian: false,
    spiceLevel: 2,
    image: "https://images.unsplash.com/photo-1545247181-516773cae754?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "16",
    category: "main-dishes",
    nameFr: "Curry crevettes",
    nameEn: "Shrimp Curry",
    descriptionFr: "Crevettes juteuses parfumées aux feuilles de cari poulé et lait de coco.",
    descriptionEn: "Juicy succulent shrimp cooked in spiced curry leaves and coconut gravy.",
    price: 3.8,
    unit: "100g",
    available: true,
    isVegetarian: false,
    spiceLevel: 2,
    popular: true,
    image: "https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "17",
    category: "main-dishes",
    nameFr: "Curry poisson",
    nameEn: "Fish Curry",
    descriptionFr: "Filets de poisson frais nappés d'une sauce curry acidulée au tamarin et graines de moutarde.",
    descriptionEn: "Fresh fish fillets gently simmered in a spiced tangy tamarind curry.",
    price: 3.8,
    unit: "100g",
    available: true,
    isVegetarian: false,
    spiceLevel: 2,
    image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "18",
    category: "main-dishes",
    nameFr: "Curry boulette de bœuf",
    nameEn: "Beef Meatball Curry",
    descriptionFr: "Boulettes de bœuf moelleuses nappées d'une sauce curry onctueuse.",
    descriptionEn: "Tender handmade beef meatballs bathed in seasoned Creole curry sauce.",
    price: 3.8,
    unit: "100g",
    available: true,
    isVegetarian: false,
    spiceLevel: 2,
    image: "https://images.unsplash.com/photo-1529042410759-befb1204b468?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "19",
    category: "main-dishes",
    nameFr: "Rougail saucisse thaï et boucané (pimenté)",
    nameEn: "Thai Sausage & Smoked Meat Rougail (Spicy)",
    descriptionFr: "Spécialité incontournable de saucisses fumées et boucané revenus aux tomates et piments.",
    descriptionEn: "Traditional spicy Creole stew with smoked sausages, pork, fresh tomatoes & thyme.",
    price: 3.5,
    unit: "100g",
    available: true,
    isVegetarian: false,
    spiceLevel: 3,
    popular: true,
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "20",
    category: "main-dishes",
    nameFr: "Curry rouge ou vert – poulet",
    nameEn: "Red or Green Chicken Curry",
    descriptionFr: "Curry thaï au poulet parfumé au basilic sacré, légumes croquants et lait de coco.",
    descriptionEn: "Fragrant Thai red or green curry with chicken, coconut milk & sweet basil.",
    price: 3.5,
    unit: "100g",
    available: true,
    isVegetarian: false,
    spiceLevel: 2,
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "21",
    category: "main-dishes",
    nameFr: "Curry rouge ou vert – crevette",
    nameEn: "Red or Green Shrimp Curry",
    descriptionFr: "Curry thaï aux crevettes fraîches mijotées dans une crème de coco épicée.",
    descriptionEn: "Thai red or green shrimp curry infused with lemongrass and coconut.",
    price: 3.5,
    unit: "100g",
    available: true,
    isVegetarian: false,
    spiceLevel: 2,
    image: "https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "22",
    category: "main-dishes",
    nameFr: "Curry rouge ou vert – saumon",
    nameEn: "Red or Green Salmon Curry",
    descriptionFr: "Pavé de saumon délicat dans une sauce coco parfumée à la citronnelle.",
    descriptionEn: "Tender salmon fillet simmered in fragrant red or green Thai coconut curry.",
    price: 3.5,
    unit: "100g",
    available: true,
    isVegetarian: false,
    spiceLevel: 2,
    image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "23",
    category: "main-dishes",
    nameFr: "Sauté de crevette",
    nameEn: "Stir-Fried Shrimp",
    descriptionFr: "Crevettes sautées au wok avec légumes croquants, sauce soja et ail.",
    descriptionEn: "Wok-tossed shrimp with crunchy seasonal vegetables and garlic glaze.",
    price: 3.5,
    unit: "100g",
    available: true,
    isVegetarian: false,
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "24",
    category: "main-dishes",
    nameFr: "Sauté d’ailes de poulet",
    nameEn: "Stir-Fried Chicken Wings",
    descriptionFr: "Ailes de poulet caramélisées au wok aux cinq épices et oignons verts.",
    descriptionEn: "Wok-fried chicken wings glazed with sweet spices and fresh spring onions.",
    price: 3.5,
    unit: "100g",
    available: true,
    isVegetarian: false,
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "25",
    category: "main-dishes",
    nameFr: "Sauté de fruits de mer",
    nameEn: "Stir-Fried Seafood",
    descriptionFr: "Mélange gourmand de crevettes, calamars et moules sautés aux herbes fraîches.",
    descriptionEn: "Fresh seafood medley stir-fried in wok with garlic, ginger, and herbs.",
    price: 3.5,
    unit: "100g",
    available: true,
    isVegetarian: false,
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "26",
    category: "main-dishes",
    nameFr: "Riz créole",
    nameEn: "Creole Rice",
    descriptionFr: "Riz blanc parfumé cuit à la méthode traditionnelle créole, parfait en accompagnement.",
    descriptionEn: "Fluffy fragrant long-grain steamed rice, the classic companion to curries.",
    price: 3.0,
    unit: "100g",
    available: true,
    isVegetarian: true,
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "27",
    category: "main-dishes",
    nameFr: "Nouilles sautées au poulet",
    nameEn: "Stir-Fried Noodles with Chicken",
    descriptionFr: "Mines frites mauriciennes au poulet, chou chinois, carottes et œuf.",
    descriptionEn: "Mauritian style stir-fried wheat noodles with tender chicken and vegetables.",
    price: 3.0,
    unit: "100g",
    available: true,
    isVegetarian: false,
    spiceLevel: 1,
    popular: true,
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "28",
    category: "main-dishes",
    nameFr: "Nouilles sautées aux légumes",
    nameEn: "Stir-Fried Vegetable Noodles",
    descriptionFr: "Nouilles au wok généreusement garnies de légumes croquants et sauce savoureuse.",
    descriptionEn: "Wok-tossed noodles with crisp seasonal vegetables and savory soy seasoning.",
    price: 3.0,
    unit: "100g",
    available: true,
    isVegetarian: true,
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "29",
    category: "main-dishes",
    nameFr: "Riz frit au poulet",
    nameEn: "Fried Rice with Chicken",
    descriptionFr: "Riz frit à la mauricienne avec dés de poulet, petits pois, carottes et ciboule.",
    descriptionEn: "Classic Mauritian fried rice sautéed with chicken chunks, peas, and eggs.",
    price: 3.0,
    unit: "100g",
    available: true,
    isVegetarian: false,
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "30",
    category: "main-dishes",
    nameFr: "Riz frit aux légumes",
    nameEn: "Vegetable Fried Rice",
    descriptionFr: "Riz sauté végétarien coloré aux légumes croquants et épices parfumées.",
    descriptionEn: "Delicious vegetarian stir-fried rice loaded with crunchy fresh vegetables.",
    price: 3.0,
    unit: "100g",
    available: true,
    isVegetarian: true,
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "31",
    category: "main-dishes",
    nameFr: "Vindaye poulpe (épice)",
    nameEn: "Spicy Octopus Vindaye",
    descriptionFr: "Plat emblématique mauricien de poulpe mariné au curcuma, graines de moutarde et piment.",
    descriptionEn: "Signature Mauritian dish of tender octopus cooked with mustard seeds, turmeric & green chilies.",
    price: 3.9,
    unit: "100g",
    available: true,
    isVegetarian: false,
    spiceLevel: 3,
    popular: true,
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "32",
    category: "main-dishes",
    nameFr: "Achard de légumes",
    nameEn: "Pickled / Spiced Mixed Vegetables",
    descriptionFr: "Condiment traditionnel croquant de carottes, chou et haricots au curcuma et moutarde.",
    descriptionEn: "Traditional spiced mustard & turmeric crunchy vegetable pickle.",
    price: 2.9,
    unit: "100g",
    available: true,
    isVegetarian: true,
    spiceLevel: 2,
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "33",
    category: "main-dishes",
    nameFr: "Haleem (soupe épicée agneau ou poulet)",
    nameEn: "Haleem (Spicy Lamb or Chicken Soup)",
    descriptionFr: "Soupe onctueuse et réconfortante mijotée aux lentilles, épices chaudes et viande.",
    descriptionEn: "Traditional wholesome slow-cooked spiced lentil and meat soup served in a box.",
    price: 8.0,
    unit: "box",
    available: true,
    isVegetarian: false,
    spiceLevel: 2,
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=600&q=80"
  },

  // ----------------------------------------------------
  // SPECIAL / ON ORDER (1 item)
  // ----------------------------------------------------
  {
    id: "34",
    category: "special",
    nameFr: "Biryani et dholl puri sur commande",
    nameEn: "Biryani & Dholl Puri (On Order)",
    descriptionFr: "Véritable Biryani mauricien cuit à l'étouffée et Dholl Puri chauds préparés spécialement sur commande.",
    descriptionEn: "Special banquet order of traditional Mauritian Dum Biryani & warm handcrafted Dholl Puri flatbreads.",
    price: null,
    unit: "sur commande",
    available: true,
    isVegetarian: false,
    isSpecialOrder: true,
    spiceLevel: 2,
    popular: true,
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80"
  },

  // ----------------------------------------------------
  // DESSERTS (3 items)
  // ----------------------------------------------------
  {
    id: "35",
    category: "desserts",
    nameFr: "Boule de coco",
    nameEn: "Coconut Ball",
    descriptionFr: "Douceur sucrée traditionnelle roulée dans de la noix de coco râpée parfumée à la cardamome.",
    descriptionEn: "Traditional Mauritian sweet coconut truffle dusted with fragrant shredded coconut.",
    price: 1.0,
    unit: "pièce",
    available: true,
    isVegetarian: true,
    spiceLevel: 0,
    popular: true,
    image: "https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "36",
    category: "desserts",
    nameFr: "Pudding maïs",
    nameEn: "Corn Pudding",
    descriptionFr: "Gâteau crémeux traditionnel à la semoule de maïs, lait de coco et vanille.",
    descriptionEn: "Traditional Mauritian sweet corn pudding cake made with coconut milk and vanilla.",
    price: 2.0,
    unit: "portion",
    available: true,
    isVegetarian: true,
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "37",
    category: "desserts",
    nameFr: "Oundé (boule de semoule de blé)",
    nameEn: "Oundé (Wheat Semolina Ball)",
    descriptionFr: "Boulette sucrée aux amandes et semoule de blé grillée parfumée à la cardamome et au ghee.",
    descriptionEn: "Roasted wheat semolina sweet confection with cardamom, ghee and toasted nuts.",
    price: 1.0,
    unit: "pièce",
    available: true,
    isVegetarian: true,
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80"
  }
];

if (typeof window !== 'undefined') {
  window.CATEGORIES = CATEGORIES;
  window.MENU_ITEMS = MENU_ITEMS;
}
